name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
        env:
          NEXT_PUBLIC_APP_URL: http://localhost:3000

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - name: Run E2E tests
        run: BASE_URL=http://localhost:3000 npm run test:e2e
        env:
          NEXT_PUBLIC_LOJA_BRINDES_BASE_URL: https://gre6bvacr5g1owv9l.lite.vusercontent.net
          NEXT_PUBLIC_APP_URL: http://localhost:3000


